name: topshoplekki
description: A booking and online shopping  application for Topshop lekki.com.ng
version: 1.0.0+1
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  #storage
  shared_preferences: ^0.5.12
  #inversion control
  get_it: ^4.0.4
  get: ^3.8.6
  #state mgmt
  stacked: ^1.5.0

  # third-party services
  stacked_services: ^0.5.4+3

  # navigation
  auto_route: ^0.6.7

  #transition
  page_transition: ^1.1.5
  #font and icons
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1

  flutter_spinkit: "^4.1.2"

  # misc
  logger: ^0.9.3

  url_launcher: ^5.7.2
  theme_mode_handler: ^2.0.0
  
  responsive_builder: ^0.1.4
  meta: ^1.1.7
  equatable: ^1.2.0

    # Firebase Related Stuff
  firebase_auth: 
  cloud_firestore:
  firebase_storage: 
  firebase_messaging: 
  firebase_analytics: 
  firebase_dynamic_links: 
  firebase_remote_config: 

  #sheets
  ndialog: ^3.0.0
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  # Generators
  build_runner: ^1.10.1

  injectable_generator: ^1.0.4
flutter:
  uses-material-design: true

fonts:
  family: Roboto
  fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Bold.ttf
      - asset: assets/fonts/Roboto-Black.ttf
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages

